### ISSUE TITLE
Question about ManifestStaticS3Storage

### ISSUE THREAD

**Issue by greenpasta** [etianen/django-s3-storage#103]
I've configured as follows:

`AWS_ACCESS_KEY_ID = 'xxxx'`
`AWS_SECRET_ACCESS_KEY = 'yyyy'`
`AWS_S3_BUCKET_NAME_STATIC = 'myapp-static'`
`AWS_S3_MAX_AGE_SECONDS = '315360000'`
`STATICFILES_STORAGE = 'django_s3_storage.storage.ManifestStaticS3Storage'`

The huge MAX_AGE is great so my visitors never have to reload static assets, if any of them change they'll have a new name. However... this also puts that MAX_AGE on `staticfiles.json`, so I think the clients also cache that basically forever and won't realize when other static assets have changed.

Is this a valid concern? Am I doing this right?

**Comment by etianen** [comment]
staticfiles.json isn't ever read by clients. It's there to be read by the
Django storage backend.

So I think you're good.

**Comment by greenpasta** [comment]
Yes, thanks! I had a different misconfiguration that led me to believe this was happening. Nothing to see here.
