### ISSUE TITLE
Upcoming changes to the Python SDK in AWS Lambda

### ISSUE THREAD

**Issue by mark-mishyn** [etianen/django-s3-storage#104]
@etianen Hello Dave!

https://aws.amazon.com/ru/blogs/compute/upcoming-changes-to-the-python-sdk-in-aws-lambda/
From AWS Compute Blog: "main changes is that the requests library was replaced with urllib3."

I'm not sure if need to worry about it. 

I see that django-s3-storage uses requests (at least in tests).

Thanks!

**Comment by etianen** [comment]
Thanks for the spot!

django-s3-storage only uses requests for testing. I don't think it will be
affected by this change. Good to keep an eye out, though. :)
