### ISSUE TITLE
Storage location folder

### ISSUE THREAD

**Issue by CBinyenya** [etianen/django-s3-storage#105]
Is there a way I can specify the storage folder or maybe easily override some of the settings with distinct classes

```
class ProfilePicStorage(S3Storage):
    bucket = 'bucket'
    path = 'media/profiles/'

```

**Comment by etianen** [comment]
You can use the AWS_S3_KEY_PREFIX setting to apply a prefix to all uploaded
files.

You can also set a prefix for individual file fields by setting
`upload_to="something"` on the file field.
