### ISSUE TITLE
Invalid bucket name, as of Feb 17, 2020

### ISSUE THREAD

**Issue by c0d5x** [etianen/django-s3-storage#107]
I always get the same error, independently of the bucket name:

`Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$"`

**Comment by etianen** [comment]
Can I see your config?

**Comment by yoyoidea** [comment]
I have the same problem:
`DEFAULT_FILE_STORAGE = 'django_s3_storage.storage.S3Storage'
STATICFILES_STORAGE = 'django_s3_storage.storage.StaticS3Storage'
AWS_REGION = "ap-northeast-1"`

**Comment by etianen** [comment]
So... you're not setting AWS_S3_BUCKET_NAME ?

**Comment by webdeveloperpr** [comment]
Same issue here

**Comment by webdeveloperpr** [comment]
```python
DEFAULT_FILE_STORAGE = 'django_s3_storage.storage.S3Storage'
STATICFILES_STORAGE = 'django_s3_storage.storage.StaticS3Storage'
# The AWS region to connect to.
AWS_REGION = 'us-east-1'
# The AWS access key to use.
AWS_ACCESS_KEY_ID = AWS_ACCESS_KEY_ID
# The AWS secret access key to use.
AWS_SECRET_ACCESS_KEY = AWS_SECRET_ACCESS_KEY
# The name of the bucket to store files in.
AWS_S3_BUCKET_NAME = 'usn-us-east-1-uat-americanheartassociation'
```

**Comment by webdeveloperpr** [comment]
After digging through the code for about 1 hr I found the problem.

Looks like I just had to add _STATIC at the end?

```python
AWS_S3_BUCKET_NAME_STATIC = 'usn-us-east-1-uat-americanheartassociation'
```

**Comment by etianen** [comment]
Ah, you were using the staticfiles storage without configuring the
staticfiles storage settings:

https://github.com/etianen/django-s3-storage#staticfiles-storage-settings

Yes, the error message could be better here. I'll look into that on Monday.

**Comment by etianen** [comment]
Pushed up 0.13.1, which gives a nice error message for several common
misconfigurations, including your own.
