### ISSUE TITLE
Is it posible to make only some files public?

### ISSUE THREAD

**Issue by mark-mishyn** [etianen/django-s3-storage#108]
Is it possible to make public some specific objects? I also use KMS-encryption, so AWS_S3_BUCKET_AUTH is True.

I've tried to use bucket policy that grants public read access to a specific object tag, but seems like it doesn't work, since S3Storage explicitly sets X-Amz-Expires based on AWS_S3_MAX_AGE_SECONDS.

**Comment by etianen** [comment]
If it's user-uploaded files, you can create a global instance of django_s3_storage.storage.S3Storage somewhere in your codebase, and assign it to a FileField or ImageField by setting `storage=`.

For static files, I can't think of a way off-hand.

**Comment by mark-mishyn** [comment]
I have one `FileField` and I have to make some files public (only within this field).

**Comment by etianen** [comment]
Then I don't think that's possible using this library.

**Comment by johnlund** [comment]
Hi @etianen, thanks for this great package.

I had a specific question here that I thought you could help out with. I'm using AWS_S3_BUCKET_AUTH = True to protect user-uploaded files on my models, but I'd like to provide my users with the ability to use CKEditor to create rich text descriptions. With the settings as they are, the CKeditor upload works, but it generates a signed/expiring URL and saves it in the textfield. After 60 minutes this URL returns a 403 error. Is there a way that I could set the files uploaded via CKEditor to `public-read` while maintaining the privacy of the files on my other models?

**Comment by etianen** [comment]
Yes!

You can create a separate instance of a
django_s3_storage.storage.S3Storage, configured to *not* use bucket auth,
and us that for your CKEditor files by passing the `storage=` param to your
filefield. Your side-wide default storage still uses bucket auth. So by
default files are private, but you can make specific file fields public.

Or, if CKEditor has to use default_storage, you can do it the other way
around, and make your default storage public, with an auth-enabled storage
you pass to all other file fields. This is less preferable, as it means
your files are default public, with opt-in private.

**Comment by johnlund** [comment]
That worked. Thank you @etianen ! :)
