### ISSUE TITLE
How to access bucket subfolders?

### ISSUE THREAD

**Issue by betancourtl** [etianen/django-s3-storage#109]
How can I set the location of the static files? I've done this before when using `django-storages` but I'm not sure how it works with this package.

This is how I have been able to set this up using `django-storages`

```python
class MediaStorage(S3Boto3Storage):
    bucket_name = 'my-app-bucket'
    location = 'media'

class StaticStorage(S3Boto3Storage):
    bucket_name = 'my-app-bucket'
    location = 'static'

```

**Comment by etianen** [comment]
The AWS_S3_KEY_PREFIX setting (suffixed with _STATIC if necessary), is what
you want.

**Comment by 4ka0** [comment]
I had exactly the same question. The following does the trick.

AWS_S3_KEY_PREFIX = 'media'
AWS_S3_KEY_PREFIX_STATIC = 'static'

@etianen: Thanks for the work on django-s3-storage. Works really well 👍
