### ISSUE TITLE
Question: Migration from OG django-storages

### ISSUE THREAD

**Issue by alexkahn** [etianen/django-s3-storage#11]
Anyone have advice on doing a migration from the OG django-storages to this storage backend?

I serve a ton of images and would like know if this would be a good fit.

I'm going to give it a go anyway and would be happy to document the process.

**Comment by etianen** [comment]
I think that the migration would be very simple, since django-s3-storage stores things identically to django-storages.

Simple change your settings to use the different storage backend, and it should work immediately. Most of the settings even have the same names!

**Comment by etianen** [comment]
Of course, a short note near the bottom of the readme might be useful if the process turns out to be arduous.

**Comment by alexkahn** [comment]
Sounds good, thanks for the prompt feedback!

**Comment by alexkahn** [comment]
Turns out this was totally trivial - there were some settings vars that needed to be changed. Noticeably `AWS_S3_BUCKET_NAME` from `AWS_STORAGE_BUCKET_NAME`.
