### ISSUE TITLE
version 0.13.1 breaks django-s3-storage on AWS using EC2 instance role

### ISSUE THREAD

**Issue by MichaelAnckaert** [etianen/django-s3-storage#110]
One of the latest changes in 0.13.1 breaks django-s3-storage when using it on an EC2 (or similar) host that depends on the instance metadata service to supply the AWS credentials. 

By only checking if the correct settings are present in the Django settings, using the instance metadata service is effectively impossible. 
Prior to this change, boto3 received credentials from the instance metadata service and django-s3-storage worked perfectly. 

Furthermore, I believe that relying on credentials being present in the Django settings file is a bad approach. Users should be encourage to either place credentials in environment variables or to have boto detect the credentials through the instance role (if present). 

If a settings check is required, a possible solution would be to try to validate the correct operation of boto3 to see if credentials were obtained in a different manner. 

The breaking change is introduced in the following commit: [e8f3cd6bf99328c882769c7349f44251ffec0df4](https://github.com/etianen/django-s3-storage/commit/e8f3cd6bf99328c882769c7349f44251ffec0df4), more exactly on [line 182 of storage.py](https://github.com/etianen/django-s3-storage/commit/e8f3cd6bf99328c882769c7349f44251ffec0df4#diff-0fa23f4eaca7fd1b21516dab5d7c4a65R182)

**Comment by etianen** [comment]
Okay, I'll take that particular setting check out first thing tomorrow.
Thanks for the heads-up.

**Comment by etianen** [comment]
Hmm. Before I do this, wouldn't it make more sense to load the
environmental variables in the settings file itself?

AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]

This is how I've always configured Django projects that use environmental
variables for config.

The recent change was prompted by people being stumped by weird error
messages when they forgot to add settings. The fact the using environmental
variables worked at all before was that the boto3 library read them in. I
had no idea it could actually do that!

**Comment by MichaelAnckaert** [comment]
If you're using environment variables then yes, your approach is correct. 

But there is a feature in AWS (and used by Boto) called instance metadata service. When using that approach, the EC2 server (or container, lambda, whatever) has access to metadata and credentials through http://169.254.169.254/latest/meta-data/. 

So in that case there are no environment variables to load in the Django settings file. Boto gets the credentials through the metadata service without any configuration. The only requirement is that the EC2 server is launched with the correct instance role (that has the right credentials). 

More information: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html

**Comment by etianen** [comment]
Oh, goodness. I really had no idea that exists.

Could you submit a MR that fixes things? I believe it's just the checks on
the auth credentials that needs to go. I'll then push out a 0.13.2 release
ASAP.

**Comment by MichaelAnckaert** [comment]
I created a PR that reverted the breaking changes. 

Thanks for being responsive to this and your efforts! I'll try and dedicate some time to update the README with information on the various authentication methods and best practices (such as using environment variables).

**Comment by etianen** [comment]
That would be great. :)

**Comment by pelme** [comment]
This is fixed in PR #111 and released in version 0.13.2 🥇 

I think this issue can be closed!

**Comment by etianen** [comment]
Yeeaaaaaaaah!
