### ISSUE TITLE
Is it possible to use this library for yandex object storage?

### ISSUE THREAD

**Issue by rnmhdn** [etianen/django-s3-storage#119]
I tried to configure it to work with yandex but I kept getting `The AWS Access Key Id you provided does not exist in our records.`

keep in mind that the same config works with django-storages.

**Comment by etianen** [comment]
django-s3-storage doesn't explicitly support or not-support yandex object
storage. It supports S3, so if something else exposes an S3-like interface,
I'd imagine it would work.

If you can figure out the source of the problem, I'd take an MR.

**Comment by aranmohyeddin** [comment]
I think it has to do with how the url is constructed.

**Comment by MichaelAnckaert** [comment]
I think you can just set the setting `AWS_S3_ENDPOINT_URL` to the correct URL (ie: `storage.yandexcloud.net`). I don't have a yandex account so can't really test it. But if the compatibility they claim is correct, this should do it.
