### ISSUE TITLE
I am defined AWS_S3_ENDPOINT_URL in settings but still use default S3 endpoint url

### ISSUE THREAD

**Issue by sunjiali** [etianen/django-s3-storage#127]
I am defined AWS_S3_ENDPOINT_URL in settings 

like:` AWS_S3_ENDPOINT_URL='https://s3.cn-northwest-1.amazonaws.com.cn'` but it still use default endpoint: 

`
<html>
<body>

api_params | {'Bucket': 'zhy-toolsset-video-prod',  'Key': 'Meeting_Recording_-_Sun_Jiali_Instant_Meeting3.mp4'}
-- | --
event_response | None
handler | <function inject_api_version_header_if_needed at 0x7fc0d6d492f0>
operation_model | OperationModel(name=HeadObject)
operation_name | 'HeadObject'
request_context | {'auth_type': None,  'client_config': <botocore.config.Config object at 0x7fc0d45e1048>,  'client_region': 'us-east-1',  'has_streaming_input': False,  'signing': {'bucket': 'zhy-toolsset-video-prod'}}
request_dict | {'body': b'',  'context': {'auth_type': None,              'client_config': <botocore.config.Config object at 0x7fc0d45e1048>,              'client_region': 'us-east-1',              'has_streaming_input': False,              'signing': {'bucket': 'zhy-toolsset-video-prod'}},  'headers': {'User-Agent': 'Boto3/1.18.9 Python/3.6.14 '                            'Linux/5.4.116-64.217.amzn2int.x86_64 '                            'Botocore/1.21.9'},  'method': 'HEAD',  'query_string': {},  'url': 'https://s3.amazonaws.com/zhy-toolsset-video-prod/Meeting_Recording_-_Sun_Jiali_Instant_Meeting3.mp4',  'url_path': '/zhy-toolsset-video-prod/Meeting_Recording_-_Sun_Jiali_Instant_Meeting3.mp4'}
self | <botocore.client.S3 object at 0x7fc0d45d0588>
service_id | 's3'
service_name | 's3'

</body>
</html>`

**Comment by etianen** [comment]
Where are you getting those API params from?

The AWS_S3_ENDPOINT_URL setting is passed into the boto3 backend. It's hard
to see how there could be a bug in django-s3-storage here.

**Comment by sunjiali** [comment]
This issue is solved.
