### ISSUE TITLE
Is there a way to get upload progress? 

### ISSUE THREAD

**Issue by sunjiali** [etianen/django-s3-storage#129]
Hi,

Is there a way to get file upload progress?

**Comment by etianen** [comment]
Up to S3, or upload from the browser to Django?

**Comment by sunjiali** [comment]
> Up to S3, or upload from the browser to Django?

Upload from the browser to Django

**Comment by etianen** [comment]
Yes, but it has nothing to do with django-s3-storage, as any solution will
work irrespective of your Django storage backend. Google for Django upload
progress, or upload progress widgets for whatever frontend framework you're
using.

**Comment by sunjiali** [comment]
Thanks for your help
