### ISSUE TITLE
Using s3_sync_meta causes TypeError exception

### ISSUE THREAD

**Issue by cvng** [etianen/django-s3-storage#13]
Anytime, I try to run `s3_sync_meta` command, that raises:
`TypeError: sync_meta_iter() missing 1 required positional argument: 'self'`

So, I end up with this small fix, which simply instantiate `storage` object before calling `sync_meta_iter()`.
I replaced in `s3_sync_meta.py`:
```python
# Sync the meta.
for path in storage.sync_meta_iter():
```
with:
```python
for path in storage().sync_meta_iter():
```
And now, I'm able to run `s3_sync_meta` as expected.

**NOTE**: This happen on `python 3.4.3`, so maybe this is related.

**Comment by etianen** [comment]
Ah, you're not using the command correctly. You should pass in the path to
a strange *instance*, not a storage class.

For example:

./manage.py s3_sync_meta django.core.files.storage.default_storage

**Comment by cvng** [comment]
Okay ;) Thanks for point me out what the good syntax is !
