### ISSUE TITLE
Caching with pre-signed url

### ISSUE THREAD

**Issue by pljspahn** [etianen/django-s3-storage#138]
The pre-signed url signature changes each time a file is requested since it's always created at a different moment.

Can I cache the pre-signed url so that it's not generated for each request? I assume in a manner like is described is this SO discussion - https://stackoverflow.com/questions/19583338/s3-signed-urls-and-caching

I haven't looked too deep into boto3, so this is maybe something that would be too awkward if not already implemented there. 

Can django-s3-storage possibly just use built-in Django cache to cache the pre-signed url passing along the expiration as set with `AWS_S3_MAX_AGE_SECONDS`?

**Comment by etianen** [comment]
Does this work for you?

https://github.com/etianen/django-s3-storage#optimizing-media-file-caching

**Comment by pljspahn** [comment]
Doesn't that merely disable private bucket access?

I was looking for a solution that keeps private buckets and instead of generating the presigned url on every request, the url is either:

1. Generated once, cached with default Django cache features, and kept until it expires, or
2. Generated from a fixed moment in time (as described in the SO link I posted above, ie "tomorrow at 12 am")

**Comment by etianen** [comment]
You'd need to subclass the storage backend to add that feature.

Beware though - caching the URL for an extended period effectively makes it
public. The default token expiry is an hour.

**Comment by pljspahn** [comment]
I'll look through the code a little more, but I'm not really sure how the token expiration is even used. The url returned from https://github.com/etianen/django-s3-storage/blob/38f6fbfd143088b7615f63bd084d5ef02b1e47c6/django_s3_storage/storage.py#L428

seems to be generated on every request. So even if the signed url is valid for one hour, the next time the page is loaded, the url returned is a _new_ signed url, which would effectively ignore the expiration since the previous signed url isn't cached anywhere and disappears into the ether.

**Comment by etianen** [comment]
You'd want to wrap and cache the 'url' method, and increase the token
expiry time.

**Comment by pljspahn** [comment]
I ended up adding a url property to my image model:

```
from django.core.cache import cache

class MyImage(models.Model):
    parent = models.ForeignKey(ParentModel, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=assign_sign_sku)

    @property
    def url(self):
        return cache.get_or_set(self, self.image.url, 1440)
```

**Comment by etianen** [comment]
Perfect!
