### ISSUE TITLE
sha1 or other hash before upload?

### ISSUE THREAD

**Issue by saberworks** [etianen/django-s3-storage#139]
Do you know of a way I could calculate the sha1 hash of a file prior to upload?  My old code (before moving files to s3) looked like this:

```
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if(self.file):
            self.file_size = self.file.file.size

            with open(self.file.path, "rb") as f:
                file_hash = hashlib.sha1()
                while chunk := f.read(8192):
                    file_hash.update(chunk)

            self.file_hash = file_hash.hexdigest()

            super().save()
```

But obviously the part where it's reading the file from disk no longer works.  Is there a way for me to intercept the file and calculate it?  Alternatively, I notice that s3 has an "etag" that might be a hash I could use (I don't know how to tell what type of hash it is), will django-s3-storage give me access to that somehow?

Thank you!

**Comment by etianen** [comment]
The etag is a usable hash, I believe.

You cab use default_storage.s3_connection to get access to a boto3
connection to query s3 metadata.

**Comment by saberworks** [comment]
Is there a way to get it if I'm not using the s3 storage as the default?  I'm actually only using it for a handful of models that allow upload of user content.  I have like `storage=s3storage` on individual file fields in the model.  Thank you!

**Comment by saberworks** [comment]
Answered my own question: the `s3_connection` is available from the specified s3storage connection as well:
```
            conn = s3storage.s3_connection
```

I'll add another comment with the working code and then close the ticket once I have it.  Thank you!

**Comment by saberworks** [comment]
It turns out the ETag is not a reliable source for a file hash.  It changes not only depending on the content of the file, but also on how it was uploaded and what type of encryption was used.  https://docs.aws.amazon.com/AmazonS3/latest/API/API_Object.html

I'm back to looking for a way to intercept the file before it's uploaded to s3.  Does it ever reside on disk anywhere?  In a temp directory or something?

Here's the working code I have to save the ETag, but it doesn't really solve the problem.

```
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if(self.file):
            self.file_size = self.file.file.size

            conn = s3storage.s3_connection

            details = conn.head_object(
                Bucket=s3bucket,
                Key=str(self.file.file),
            )

            self.file_hash = details.get("ETag").replace('"', '')

            super().save()
```

**Comment by etianen** [comment]
When the file is first uploaded it will be stored in memory or in a temp
file. This is normal Django file handling, and nothing to do with this
plugin.

I think the file may still be in this state before you call super().save()

If not, you might have to intercept it at the model form stage.

**Comment by etianen** [comment]
Then use s3storage.s3_connection :)
