### ISSUE TITLE
Issue when upgrading to version 0.13.5 or higher

### ISSUE THREAD

**Issue by apiljic** [etianen/django-s3-storage#145]
I am upgrading an application to django 3 and experienced an issue with the latest version of this library (0.13.8). The last version which works for me is 0.13.4.

Currently, I have installed:
```
Django==3.2.15
django-imagekit==4.1.0
django-s3-storage==0.13.4
Pillow==9.2.0
```
This combination works. However, with version 0.13.5 or higher, I get an error. I also tried to downgrade the django-imagekit and Pillow, but the error is still there.

Does someone know what change I need to make to be able to use the latest version of this library?

The traceback:

> Traceback (most recent call last):
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
>     current = current[bit]
> 
> During handling of the above exception ('ImageCacheFile' object is not subscriptable), another exception occurred:
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 552, in wrapper
>     return wrapped(*args, **kwargs)
>   File "/app/apps/news/views.py", line 64, in latest
>     return render(request, "news/list.html", data)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
>     content = loader.render_to_string(template_name, context, request, using=using)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
>     return template.render(context, request)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
>     return self.template.render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 170, in render
>     return self._render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 147, in dynamic_wrapper
>     return wrapped(*args, **kwargs)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
>     return self.nodelist.render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 938, in render
>     bit = node.render_annotated(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
>     return self.render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
>     return compiled_parent._render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 147, in dynamic_wrapper
>     return wrapped(*args, **kwargs)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
>     return self.nodelist.render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 938, in render
>     bit = node.render_annotated(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
>     return self.render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 774, in wrapper
>     return FunctionTraceWrapper(wrapped, name=instance.name, group='Template/Block')(*args, **kwargs)
>   File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 166, in literal_wrapper
>     return wrapped(*args, **kwargs)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
>     result = block.nodelist.render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 938, in render
>     bit = node.render_annotated(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
>     return self.render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/defaulttags.py", line 214, in render
>     nodelist.append(node.render_annotated(context))
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
>     return self.render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/library.py", line 234, in render
>     return t.render(new_context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 172, in render
>     return self._render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 147, in dynamic_wrapper
>     return wrapped(*args, **kwargs)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
>     return self.nodelist.render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 938, in render
>     bit = node.render_annotated(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
>     return self.render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
>     return nodelist.render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 938, in render
>     bit = node.render_annotated(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
>     return self.render(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 988, in render
>     output = self.filter_expression.resolve(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
>     obj = self.var.resolve(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
>     value = self._resolve_lookup(context)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 837, in _resolve_lookup
>     current = getattr(current, bit)
>   File "/app/.heroku/python/lib/python3.8/site-packages/imagekit/cachefiles/__init__.py", line 85, in url
>     return self._storage_attr('url')
>   File "/app/.heroku/python/lib/python3.8/site-packages/imagekit/cachefiles/__init__.py", line 75, in _storage_attr
>     existence_required.send(sender=self, file=self)
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
>     return [
>   File "/app/.heroku/python/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
>     (receiver, receiver(signal=self, sender=sender, **named))
>   File "/app/.heroku/python/lib/python3.8/site-packages/imagekit/registry.py", line 53, in existence_required_receiver
>     self._receive(file, 'on_existence_required')
>   File "/app/.heroku/python/lib/python3.8/site-packages/imagekit/registry.py", line 61, in _receive
>     call_strategy_method(file, callback)
>   File "/app/.heroku/python/lib/python3.8/site-packages/imagekit/utils.py", line 166, in call_strategy_method
>     fn(file)
>   File "/app/.heroku/python/lib/python3.8/site-packages/imagekit/cachefiles/strategies.py", line 15, in on_existence_required
>     file.generate()
>   File "/app/.heroku/python/lib/python3.8/site-packages/imagekit/cachefiles/__init__.py", line 94, in generate
>     self.cachefile_backend.generate(self, force)
>   File "/app/.heroku/python/lib/python3.8/site-packages/imagekit/cachefiles/backends.py", line 109, in generate
>     self.generate_now(file, force=force)
>   File "/app/.heroku/python/lib/python3.8/site-packages/imagekit/cachefiles/backends.py", line 96, in generate_now
>     file._generate()
>   File "/app/.heroku/python/lib/python3.8/site-packages/imagekit/cachefiles/__init__.py", line 103, in _generate
>     content.seek(0)
> 
> Exception Type: ValueError at /news/latest/
> Exception Value: I/O operation on closed file.

**Comment by etianen** [comment]
I've put a potential fix into the master branch. Can you try it out and let me know if it works for you?

**Comment by apiljic** [comment]
The code in the master branch seems to work. I just tried it and got no errors.
I assume the fix will be in the 0.13.9 release. Thanks a lot!

**Comment by etianen** [comment]
Yup! 0.13.9 is out now :)

**Comment by apiljic** [comment]
Perfect. Thank you very much!
