### ISSUE TITLE
Huge Thanks

### ISSUE THREAD

**Issue by Routhinator** [etianen/django-s3-storage#149]
Since this repo doesn't have discussions, I just have to give a huge thanks and props to the devs and maintainers here. 

I yanked django-storages out in favour of this module and my application import process that brings in 3000 users and their avatars has dropped in duration of execution by 60% and memory usage has similarly dropped. 

Well done! :partying_face:

**Comment by etianen** [comment]
❤️ 
I've never benchmarked the two implementations, but that's pleasantly suprising nonetheless! Thanks!

**Comment by mgalgs** [comment]
Here here!
