### ISSUE TITLE
Support windows

### ISSUE THREAD

**Issue by bpbp-boop** [etianen/django-s3-storage#15]
Currently, if you run collectstatic on a windows environment paths get uploaded with windows-style path separators.

Example:
https://s3-ap-southeast-2.amazonaws.com/nextgame-images/admin%5Ccss%5Cbase.css

It would be great if this could automatically convert the paths to the correct unix-style path separators

**Comment by etianen** [comment]
Yuck! Well, I'm happy to take a pull request (with tests) for this, or I'll have a look myself over the next few weeks.

I'm surprised that Django doesn't do the conversion itself in the collectstatic command. If django-s3-storage was to just convert all backslashes to forward slashes in filenames, then it would make it impossible to use backslashes at all, which someone might want to do for some reason.

Still, I guess some extra logic in _get_key_name of the storage class would fix this.

**Comment by xblitz** [comment]
also just ran into this problem :/

**Comment by etianen** [comment]
Check out the latest master. The fix there will hopefully solve your issue. :)

**Comment by bpbp-boop** [comment]
Awesome, thanks! :)
