### ISSUE TITLE
Document the `AWS_S3_MAX_POOL_CONNECTIONS` setting

### ISSUE THREAD

**Issue by amrishparmar** [etianen/django-s3-storage#151]
The new `AWS_S3_MAX_POOL_CONNECTIONS` added in https://github.com/etianen/django-s3-storage/pull/148 is legitimately useful (we previously had to create a custom class to override this behaviour), but it appears to be missing from the README.

**Comment by etianen** [comment]
Fixed in #155 082614760d950055a14176dece98f7460da4162f
