### ISSUE TITLE
Cannot open files in plain text mode

### ISSUE THREAD

**Issue by arveitch** [etianen/django-s3-storage#160]
I am working with CSV files which need to be opened in plain text mode. With django-storage I had been using:

    with object.file.open('r') as f:
        csv_reader = csv.DictReader(f)

But that gives me an error and I need to open it in binary mode and do this instead:

    with object.file.open() as f:
        csv_reader = csv.DictReader(io.StringIO(f.read().decode('utf-8'))

I'm wondering if this is a bug or if this is how my code should change.

(I am loving the product, I like that it seeks(0) and handles encoding properly when I am writing CSV files. It is much closer to the the native Django Storage.)

**Comment by etianen** [comment]
It's a bug!

And I just fixed it (but only for Python 3.11+) 🙇 

Please upgrade to 0.15.0

**Comment by arveitch** [comment]
Thanks for fixing this so quickly! I'm on Python 3.11 so that's fine.

I think it's a great product, it deserves to be much more widely known about.
