### ISSUE TITLE
Setting to disable GZIP compression?

### ISSUE THREAD

**Issue by Bartvds** [etianen/django-s3-storage#17]
Amazon CloudFront recently added (opt-in) support for auto-magic transparent GZIP compression.

This means it is no longer needed to pre-compress the S3 objects for gzipped serving over HTTP if you use CloudFront and opted in to this. 

So it would be cool if we'd have a setting to disable the GZIP compression in django-s3-storage (maybe with a use-case note in the readme in case people missed [the CF announcement](https://aws.amazon.com/blogs/aws/new-gzip-compression-support-for-amazon-cloudfront/)).

**Comment by etianen** [comment]
What would be achieved by no pre-compressing the content, out of interest?
Does it break the cloudfront compression, or is it just unecessary?

**Comment by Bartvds** [comment]
Sorry for my late reply. Pre-compressing doesn't break anything, it is just not necessary.

One huge benefit of letting CF do the GZIP is that the S3 bucket now contains the plain bytes, so they are usable for non-gzip enabled tools. Eg: if you pull some files out of the bucket with a random S3 viewer or wrapper you won't have to inspect each file and decompress it manually.

And it improves consistency: if we let CF do the GZIP we can drop updated files in the bucket with any external tools instead of having to move them though django collectstatic.

**Comment by etianen** [comment]
Seems reasonable! I'll take a pull request for this feature. :)
