### ISSUE TITLE
Files being overwritten.

### ISSUE THREAD

**Issue by ankgt** [etianen/django-s3-storage#25]
I have a test model with a FileField. I find that if I create two objects of this model, and both objects have the same file name, the second object I create, overwrites the file on S3. 

For example, the filename of the first object is test.pdf. 

If I create a second object with the same file name test.pdf (but different contents), the test.pdf on S3 gets overwritten, and the first model also now refers to the new test.pdf.

Is this normal behaviour?

Thanks.

**Comment by ankgt** [comment]
A solution to my own problem. I am very new to programming so please excuse my mistake.

It seems that in my case, i had set the upload_to field on the model with a starting /, so in this case '/images' instead of 'images/'. Because of this the exists() method in the storage class is not working correctly. 

I have fixed it now.

Thank you. This addon has really saved me. The django-storages just does not work properly with a news S3 instance that requires aws4-hmac-sha256.

**Comment by etianen** [comment]
I suspect that this is now fixed in the master branch, in any case. :)

**Comment by etianen** [comment]
And now released as 0.9.10!

**Comment by ankgt** [comment]
Thanks!
