### ISSUE TITLE
Exists method returning a false positive

### ISSUE THREAD

**Issue by leonsmith** [etianen/django-s3-storage#27]
The exists method returns a false positive when a file with a similar name exists within the bucket.

I did comment on the comment on the commit in question but have copied is here for completeness.

https://github.com/etianen/django-s3-storage/commit/027dcdf4185f97d8317965e6450d5378ddc5155b

```
This causes false positives for keys that have the same prefix.

"css/main.css.map" existing on s3 for "css/main.css" would cause this to return true.

Do we need to check for directory existence in this method? the docs state this is just for files?
```

Looking further this looks like it was changed in relation to #16 the [Django docs](https://docs.djangoproject.com/en/1.9/ref/files/storage/#django.core.files.storage.Storage.exists) does state 

> Returns True if a file referenced by the given name already exists in the storage system, or False if the name is available for a new file.

But is is used with a directory in the `collectstatic --clear` command: https://github.com/django/django/blob/master/django/contrib/staticfiles/management/commands/collectstatic.py#L106

**Comment by etianen** [comment]
I've just pushed a potential fix to master. Could you let me know if it works for you?
