### ISSUE TITLE
Signature mismatch error

### ISSUE THREAD

**Issue by scythargon** [etianen/django-s3-storage#28]
Hi! I get
`boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.`
when try to `collectstatic`, though credentials are fine - works perfectly with this library https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html

**Comment by etianen** [comment]
Can you post the full traceback please?

What region are you using? And what versino of django-s3-storage?

**Comment by dedayoa** [comment]
I had the same issue, "S3ResponseError...". Tested storages and that worked fine...I however dumped the idea of storing (actually caching files) to S3

**Comment by etianen** [comment]
@scythargon - try using the master branch. A possible fix has been uploaded (it's a boto bug, fixed by #30)
