### ISSUE TITLE
Replace boto with boto3

### ISSUE THREAD

**Issue by mehtadhaval** [etianen/django-s3-storage#29]
Is there any plan to replace boto with boto3 ? The developers at boto prefer say that it is stable enough and projects should start integrating boto3.

**Comment by etianen** [comment]
What advantage does using boto3 give, in this case?

No plan as yet, but happy to consider for a compelling reason.

**Comment by mehtadhaval** [comment]
I was actually trying to implement a feature, where you can specify a folder inside the bucket in which media / static files would be stored. another package django-s3-folder-storage has this feature, from which, I could copy it, but it depends on boto3, so I just wanted to know whether there are any plans to integrate boto3.

**Comment by etianen** [comment]
I think that feature is already implemented by the `AWS_S3_KEY_PREFIX` and `AWS_S3_KEY_PREFIX_STATIC` settings, isn't it?

**Comment by mehtadhaval** [comment]
Oh ok. I thought those settings added a prefix to a file name, not the path. Thanks.

**Comment by etianen** [comment]
It adds a prefix to the key. S3 doesn't have any concept of folders. If the you include a slash in the filename, it's in a "folder". So a prefix of "foo/" puts it in the folder "foo".
