### ISSUE TITLE
Could you push a release to PyPI?

### ISSUE THREAD

**Issue by aaugustin** [etianen/django-s3-storage#34]
Hello,

I've been applying the patch from #26 to projects where I need it. I'd love to use an off-the-shelf version of django-s3-storage instead. When you have time, would it be possible to make a release?

Thanks!

**Comment by etianen** [comment]
It is done!

https://pypi.python.org/pypi/django-s3-storage/0.9.11

**Comment by aaugustin** [comment]
Thanks Dave!
