### ISSUE TITLE
Library not compressing uploaded files

### ISSUE THREAD

**Issue by ofersto** [etianen/django-s3-storage#35]
Hi,
I tried to use this library for uploading django files to AWS S3 especially because it allows to compress files, but it doesn't work. Even when I tried to manually define AWS_S3_GZIP = True.

Please help

**Comment by etianen** [comment]
It does work!

Files are only stored compressed if their compressed size is smaller than their uncompressed size. They are also only compressed if they are detected to be plain text, json, javascript, css, html or XML.

What files are you trying to store compressed?
