### ISSUE TITLE
0.9.11 ManifestStaticS3Storage incompatible with django-grappelli 2.9.1 / django 1.10

### ISSUE THREAD

**Issue by melinath** [etianen/django-s3-storage#36]
I'm getting the following error:

```
Post-processing 'grappelli/tinymce/jscripts/tiny_mce/themes/simple/skins/o2k7/ui.css' failed!
[...]
ValueError: The file 'grappelli/tinymce/jscripts/tiny_mce/themes/simple/skins/o2k7/../../img/icons.gif' could not be found with <django_s3_storage.storage.ManifestStaticS3Storage object>.
```

Here's some relevant shell code:

```
 >>> storage.exists('grappelli/tinymce/jscripts/tiny_mce/themes/simple/skins/o2k7/../../img/icons.gif')
False
>>> storage.exists('grappelli/tinymce/jscripts/tiny_mce/themes/simple/img/icons.gif')
True
```

FWIW this broke when I upgraded django and grappelli, not when I upgraded django-s3-storage. But it seems like a bug in the storage somehow maybe? I don't see anything relevant in the 1.10 release notes.

**Comment by etianen** [comment]
This is because the CSS references a non-existent image file. It will
happen with any storage backed that inherits Django's manifest or cached
storage backends.

The solution is to fix the CSS, or use the basic StaticS3Storage class.

**Comment by melinath** [comment]
I'm pretty sure the file did exist, though to be fair I didn't say that explicitly.

**Comment by melinath** [comment]
@etianen As you can see from the example I gave, the file _does_ exist. The storage says it exists if I give a direct path to it. And yet the storage does not find it with the additional two dirs plus `../..`.

**Comment by etianen** [comment]
Check out django-s3-storage v0.11.0. This should be fixed.

**Comment by melinath** [comment]
Cool, thanks.
