### ISSUE TITLE
IOError: S3Storage error on Heroku

### ISSUE THREAD

**Issue by dbinetti** [etianen/django-s3-storage#42]
With version 0.11.0, Python 2.7.13

I ran the `collectstatic` command manually, from a Heroku bash shell with `--clear`.  I then tried to do an automated build (normal Heroku deploy) and got this error.

```
-----> Python app detected
     $ pip install -r requirements.txt
     $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "manage.py", line 11, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
           output = self.handle(*args, **options)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 193, in handle
           collected = self.collect()
         File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
           handler(path, prefixed_path, storage)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 349, in copy_file
           if not self.delete_file(path, prefixed_path, source_storage):
         File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 258, in delete_file
           target_last_modified = self.storage.get_modified_time(prefixed_path)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/files/storage.py", line 230, in get_modified_time
           dt = self.modified_time(name)
         File "/app/.heroku/python/lib/python2.7/site-packages/django_s3_storage/storage.py", line 322, in modified_time
           return make_naive(self.meta(name)["LastModified"])
         File "/app/.heroku/python/lib/python2.7/site-packages/django_s3_storage/storage.py", line 32, in _do_wrap_errors
           raise IOError("S3Storage error at {!r}: {}".format(name, force_text(ex)))
       IOError: S3Storage error at u'rest_framework/fonts/glyphicons-halflings-regular.woff': An error occurred (404) when calling the HeadObject operation: Not Found
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
```

Downgrading to 0.9.11 resolved the issue.

**Comment by etianen** [comment]
I've just pushed a commit to master that will probably fix this.

It appears that you hit a funny race condition, followed by a bug that only occurs in Python 2.7.

The race condition was that, somehow, `rest_framework/fonts/glyphicons-halflings-regular.woff` was deleted between django checking that it `exists()`, and then getting it's `modified_time()`.

The Python 2.7 bug is that S3Storage throws an `IOError`, which is not the same as an `OSError` in Python 2.7, so it wasn't caught by collectstatic. The commit I've made changes S3Storage to throw an OSError, which should fix your problem.

**Comment by dbinetti** [comment]
`master` now works. thanks.

that said, it is re-uploading all assets on every build.  not sure if
that's because I'm going off master, but FWIW that is currently
happening...  I'll file an issue if it still occurs when I'm loading from
PyPi

**Comment by etianen** [comment]
Unfortunately, the collectstatic command only appears to skip uploading if
the storage implements path(), which this one doesn't, for obvious reasons.

I'm wondering why this is the case. It doesn't sound like desirable
behaviour.

**Comment by dbinetti** [comment]
is this a new feature of 0.11?  v. 0.9.11 does not upload redundant
objects....

**Comment by etianen** [comment]
I'm pretty sure this behavior is linked to Django version. In 1.10.0, it looks like you need a local path to skip uploading:

https://github.com/django/django/blob/1.10/django/contrib/staticfiles/management/commands/collectstatic.py#L276

However, if you look at the Django 1.10.5 code, this issue appears to have been fixed:

https://github.com/django/django/blob/1.10.5/django/contrib/staticfiles/management/commands/collectstatic.py#L283

**Comment by dbinetti** [comment]
I read the source code, but I'm afraid I'm missing the context and don't
understand how this affects the library.

so please forgive me for persisting, but let me recap for clarity:

- I'm on Django 1.10.5, python 2.7.13.
- Deploying on Heroku, via Semaphore (continuous integration service)
- the deployment is initiated through GitHub, via a `git push --force
heroku $BRANCH_NAME:master` sent through Semaphore.

With that, on v0.9.11 of DSS ( my shorthand for django-s3-storages), I get
the expected behavior: the `collectstatic`  command, run by default, skips
unmodified files.

However, on v.0.11 or DSS, all static files are uploaded, every time,
regardless if they have ever been modified.


There is an interesting exception to the above; namely, that under 0.9.11
is skips all files save for *one*.

<investigating....>


And here are some results of my investigation:

The offending file is the same
`rest_framework/fonts/glyphicons-halflings-regular.woff` my file that you
noticed before.  When looking in my bucket there are many versions of the
file, all with an appended hash; i.e., it just is creating a new copy of
that particular file on every upload.  [screenshot](
https://www.dropbox.com/s/737dzpusn0rvp4v/Screen%20Shot%202017-02-13%20at%2011.39.34%20AM.png?dl=0
)

So I did some poking around and discovered the following, all related to
that specific file:

[aws s3 sync doesn't guess MIME type for .woff file](
https://github.com/aws/aws-cli/issues/1249)

[Bootstrap 3 Glyphicons are not working](
http://stackoverflow.com/questions/18369036/bootstrap-3-glyphicons-are-not-working
)

[Glyph icons don't work in the customized version](
https://github.com/twbs/bootstrap/issues/9925)

[collectstatic can't find glyphicons when using ManifestStaticFilesStorage](
https://github.com/tomchristie/django-rest-framework/issues/2008)

[Add Glyphicons font files to solve collectstatic issue](
https://github.com/tomchristie/django-rest-framework/pull/2024)

My first thought was that DRF uploaded a corrupt file to its `static`
files, but its the same checksum for both the DRF version and what's in the
Bootstrap `dist`.  So it might be the AWS mime-type issue.

Anyway, I think you're in a much better position to determine if it is one
of these issues (or something else.).

<closed investigation>

On the main topic, the question for me still remains which is why the
desired behavior works (aside from the exception) on an older version of
DSS but not the most current when the versions of Django are identical.

Thanks!
Dave



On Mon, Feb 13, 2017 at 10:50 AM, Dave Hall <notifications@github.com>
wrote:
>
> I'm pretty sure this behavior is linked to Django version. In 1.10.0, it
looks like you need a local path to skip uploading:
>
>
https://github.com/django/django/blob/1.10/django/contrib/staticfiles/management/commands/collectstatic.py#L276
>
> However, if you look at the Django 1.10.5 code, this issue appears to
have been fixed:
>
>
https://github.com/django/django/blob/1.10.5/django/contrib/staticfiles/management/commands/collectstatic.py#L283

**Comment by etianen** [comment]
Okay, I've logged this as a new issue, here: #43

I'll have an investigate in a week or so. I'm afraid I'm pushing for a deadline at the moment.

**Comment by dbinetti** [comment]
of course!  thank you for producing the library in the first place!

**Comment by etianen** [comment]
Switching to boto3 seemed necessary, given that they've stopped really caring about boto2. However, boto3 has been a bit of a disappointment. It's very un-Pythonic, and the docs are a huge maze of confusion. So there will be some wrinkles like this!
