### ISSUE TITLE
S3 custom domain and collectstatic

### ISSUE THREAD

**Issue by dionysio** [etianen/django-s3-storage#44]
I have a cdn.domain.com that points to a s3 bucket with the same name. In my settings for this app I've added:

```
AWS_S3_CALLING_FORMAT_STATIC = 'boto.s3.connection.VHostCallingFormat'
AWS_S3_HOST_STATIC = 'cdn.domain.com'
```
and URLs that are generated by {% static %} now work properly. I still have one problem though - when I run collectstatic command I get:

```
<Error>
    <Code>InvalidRequest</Code>
    <Message>
        The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
    </Message>
    <RequestId>FCA19FC7046E571A</RequestId>
    <HostId>...</HostId>
</Error>
```

If I remove AWS_S3_CALLING_FORMAT_STATIC and AWS_S3_HOST_STATIC settings then collectstatic runs fine and I can see files being uploaded to S3. Am I missing some other setting here?

**Comment by etianen** [comment]
Try using just the AWS_S3_CALLING_FORMAT_STATIC setting

**Comment by dionysio** [comment]
Different kind of error pops up:

```
<Error>
    <Code>AuthorizationHeaderMalformed</Code>
    <Message>The authorization header is malformed; the region 'cdn' is wrong; expecting 'eu-central-1'</Message>
    <Region>eu-central-1</Region>
    <RequestId>EB5E328FFBC0D2DD</RequestId>
    <HostId>...</HostId>
</Error>
```

**Comment by etianen** [comment]
Hmm. Can you try using the latest release of the library? It's been
upgraded to use the latest libs from Amazon, so might be better.

You'll need to change:

AWS_S3_CALLING_FORMAT_STATIC = 'boto.s3.connection.VHostCallingFormat'

To:

AWS_S3_ADDRESSING_STYLE = "virtual"
