### ISSUE TITLE
Files not updated on s3

### ISSUE THREAD

**Issue by Nizebulous** [etianen/django-s3-storage#46]
I am trying to push a change to some css files that I have and they aren't overwriting the existing files on s3 even though they had changed. I saw the other issue #43 and thought that this might be related to that "fix". So I'm trying to use 0.11.0. I will let you know how that goes.
This is on Django 1.10.5 and Python 3.4 (on elastic beanstalk).

**Comment by Nizebulous** [comment]
anecdotally, the downgrade seemed to work.

**Comment by etianen** [comment]
Are you sure they aren't overwriting the css files? Try clearing your
browser cache, as the files have a long expiry time.

The AWS_S3_MAX_AGE_SECONDS_STATIC setting can be set to 0 to disable this
caching behaviour. Alternatively, use the
django_s3_storage.storage.ManifestStaticS3Storage backend, which has cache
busting capabilities.

**Comment by Nizebulous** [comment]
Yeah...I was doing hard-refreshes in my browser that caused me to look on S3....and the timestamp on the file in s3 (including the contents of the file) were not updating.
I will checkout ManifestStaticS3Storage backend in any case for the cache busting capabilities.

**Comment by etianen** [comment]
Try using 1.11.1. This fixes an issue with detecting modified files on S3.

**Comment by etianen** [comment]
The AWS_S3_FILE_OVERWRITE setting, new in 0.11.3, will almost certainly help here.
