### ISSUE TITLE
Each collectstatic generates a new available name for certain specific files

### ISSUE THREAD

**Issue by Bartvds** [etianen/django-s3-storage#48]
We have the weirdest issue where every collectstatic copies a specific file to S3 under a new random name (looks like it is generated by the storage API's [`get_available_name()`](https://docs.djangoproject.com/en/1.11/ref/files/storage/#django.core.files.storage.Storage.get_available_name)).  This is of course very problematic as it break URL's

In the current project it does this for a .woff file from fontawesome  (the one from the [django-suit V2 preview](https://github.com/darklow/django-suit/tree/v2/suit/static/suit/fonts)). 

In another projects this happens for a few different files.

Example, note only this particular `.woff` file gets duplicated. The weird thing is that the original file name (without the random postfix) is missing. 

I feel this might have something to do with eventual consistency?  It looks like storage gets syncing, somehow thinks the files changed (incorrectly), then tries to replace it with a delete and create, but hitting a race condition between the delete and create in django's storage mechanism?

![image](https://cloud.githubusercontent.com/assets/685984/25947129/73605816-364e-11e7-9226-4a5c08e68313.png)

This is deployed from EC2 on the official Ubuntu 16 AMI with python 3.6, django 1.11, django-s3-storage 0.11.1. This particular .woff file comes from a "pip install -e git+git://.." directly from django-suit's github.

**Comment by etianen** [comment]
I think you need to update your machine's mimetypes database. More info here: #45

**Comment by Bartvds** [comment]
TIL, it was indeed listed as `application/x-font-woff ` instead of `application/font-woff `.

Weird how that old mimetype is still lingering everywhere, this was supposedly all new and freshly provisioned software. 😉 

Thanks for the advice!

**Comment by LennyLip** [comment]
@etianen Hello, I have the same problem with css!
![css](https://user-images.githubusercontent.com/955994/36948675-7c29f566-1fef-11e8-80bd-e8174ac02926.png)

**Comment by LennyLip** [comment]
@etianen I have same bug with css 
![css](https://user-images.githubusercontent.com/955994/36948731-6eeb2630-1ff0-11e8-9f68-1d09af49319b.png)

**Comment by etianen** [comment]
Yeah, this was fixed recently.
