### ISSUE TITLE
django s3 storages does not recognise the bucket name

### ISSUE THREAD

**Issue by KakarN** [etianen/django-s3-storage#53]
I am using django-s3-storage==0.11.2 and boto3==1.4.4. These are in the settings.py:

```
	STATIC_URL = '/static/'
	STATICFILES_DIRS = [
	    os.path.join(BASE_DIR, "static"),
	]
	STATIC_ROOT = os.path.join(BASE_DIR, 'static_cdn')
	MEDIA_URL = '/media/'
	MEDIA_ROOT = os.path.join(BASE_DIR, 'media_cdn')

	AWS_S3_BUCKET_NAME = "my-bucket-name"
	AWS_ACCESS_KEY_ID = 'test_id_x'
	AWS_SECRET_ACCESS_KEY = 'test_id_x+test_id_x'
	DEFAULT_FILE_STORAGE = "django_s3_storage.storage.S3Storage"
	STATICFILES_STORAGE = "django_s3_storage.storage.StaticS3Storage"
	AWS_S3_ADDRESSING_STYLE = "auto"
	AWS_S3_BUCKET_AUTH_STATIC = False
	AWS_S3_MAX_AGE_SECONDS_STATIC =  60 * 60 * 24 * 365  # 1 year.
	AWS_S3_BUCKET_AUTH = False
	AWS_S3_MAX_AGE_SECONDS = 60 * 60 * 24 * 365  # 1 year.
```

I have also ran these command:

`    manage.py s3_sync_meta django.core.files.storage.default_storage`

But when I run `collectstatic` or this command

`	manage.py s3_sync_meta django.contrib.staticfiles.storage.staticfiles_storage`

I get this error:

> 	botocore.exceptions.ParamValidationError: Parameter validation failed:
> 	Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$"

I have already created the bucket, and the bucket name is correct, because this works and does not gives any error:

    `s3.meta.client.head_bucket(Bucket='my-bucket-name')`

I don't know what am I missing here? Could you help me out please.

**Comment by matthiask** [comment]
Sounds like a problem loading settings; the bucket name in the error message is an empty string.

What is the value of `django.conf.settings.AWS_S3_BUCKET_NAME` in the Django shell?

**Comment by etianen** [comment]
I think you need to specify AWS_S3_BUCKET_NAME_STATIC in your settings file.
