### ISSUE TITLE
In some instances, files are not getting copied over to s3 correctly.

### ISSUE THREAD

**Issue by kencochrane** [etianen/django-s3-storage#55]
Depending on what you have for file names, some of the files are not getting copied over correctly.

If you have the following two files:
- assets/bootstrap/css/bootstrap.min.css.map
- assets/bootstrap/css/bootstrap.min.css

It will copy over the first one `bootstrap.min.css.map` but it will not copy over the second one `bootstrap.min.css`. This is because of the way we determine if a file exists or not.

Look at the exists method found here: https://github.com/etianen/django-s3-storage/blob/master/django_s3_storage/storage.py#L269

```
    def exists(self, name):
        # We also need to check for directory existence, so we'll list matching
        # keys and return success if any match.
        results = self.s3_connection.list_objects_v2(
            Bucket=self.settings.AWS_S3_BUCKET_NAME,
            MaxKeys=1,
            Prefix=self._get_key_name(name),
        )
        return bool(results["KeyCount"])
```
What this method does is it will do a listing of the bucket using the prefix of the given name. When it wants to see if `assets/bootstrap/css/bootstrap.min.css` exists it will list the contents of the bucket, using the prefix of `assets/bootstrap/css/bootstrap.min.css` and return at most 1 key.

This method will return `True` even if `assets/bootstrap/css/bootstrap.min.css` isn't there if the `assets/bootstrap/css/bootstrap.min.css.map` file is there because the prefix of `assets/bootstrap/css/bootstrap.min.css` matches the file `assets/bootstrap/css/bootstrap.min.css.map`. So you end up with a false positive. If the files doesn't exists, it will use the `get_available_name()` method from here: https://github.com/django/django/blob/master/django/core/files/storage.py#L60 to generate a random file name and store that.

What happens is that the file is copied over, but the name was changed, and thus is unavailable when you try and fetch from s3 directly.

The fix is to do something like this.

```
    def exists(self, name):
        try:
            self.s3_connection.head_object(
                Bucket=self.settings.AWS_S3_BUCKET_NAME,
                Key=self._get_key_name(name))
            return True
        except ClientError as e:
            if e.response['Error']['Code'] == "404":
                return False
            else:
                raise e
```
This code makes a head call for the object, and if it returns with no error, you know it exists, if it returns an error, check to make sure it is a 404, and not another error. If a 404, then we know the file doesn't exists.

Similar code can be found here: https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L452-L467 and https://stackoverflow.com/questions/33842944/check-if-a-key-exists-in-a-bucket-in-s3-using-boto3

I can submit a PR for the fix, but I had one question around the comment in the exists method.

```
  # We also need to check for directory existence, so we'll list matching
  # keys and return success if any match.
```
It says that we need to also check for directory existence. My code from above doesn't work for directories, so we will need a solution for that use case. Do you know if that comment is still relevant?

**Comment by etianen** [comment]
Excellent bug report. Unfortunately, a satisfactory solution is going to be
difficult.

My understanding is that exists() should also handle the case of a
directory. Unfortunately, on S3, directories don't ever exist! This means
that we can only tell if a directory exists if at least one key starts with
the directory prefix.

However, the more I think about it, the more the current solution is
broken. After all, a key of foo/bar will currently return exists() = true
for "f", "fo", "foo", "foo/" etc, which is clearly wrong.

How about this: For a key of "foo", it will try to head_object for "foo"
and "foo/". If either return true, then the file or directory exists.

Unfortunately, that means two head_requests to ensure a missing file is
actually missing. The best algorithm I can come up with is:

   1. If the key ends with "/", return whether if it exists.
   2. Otherwise, check if the key exists. If it does, return true,
   otherwise, goto 1.

This means that things that are obviously directories only need 1 head
request. Things that might be files need 1 head request if it exists, and
two if it does not.

**Comment by kencochrane** [comment]
@etianen this might be a naive question, but why do we care if a directory exists? When you write files to s3, you need two things the key and the value. The key can be "blah" or something like "foo/bar/blah", they are the same according to s3, unlike a normal filesystem, you don't need to have the directory structure built up before you save the file in a directory.

Is it so that we can create empty directories on s3? 

Looking at the other django s3 storage libraries they don't seem to care about directories in their exists, but they are doing something a little different, they are using bucket.Object('key').load() and if that fails they return false. The Object().load() will throw an error if it is a directory which returns false if a directory exists.

If that happens what is the worse thing, it tries to create the key/directory again? Since it is empty, it might not be a big deal.

#### Code from django-storages: s3boto3.exists()

https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L457-L472

```
   def exists(self, name):
        if not name:
            try:
                self.bucket
                return True
            except ImproperlyConfigured:
                return False
        name = self._normalize_name(self._clean_name(name))
        if self.entries:
            return name in self.entries
        obj = self.bucket.Object(self._encode_name(name))
        try:
            obj.load()
            return True
        except self.connection_response_error:
            return False
```

**Comment by etianen** [comment]
It looks like collectstatic --clear will abort early if the directory
doesn't exist. So I think we do need to support it.

I guess the other S3 libraries simply don't support collectstatic --clear...

**Comment by kencochrane** [comment]
OK, thanks for the info, I wasn't aware of the collectstatic --clear requirement. I think what you proposed above seems reasonable, it might make things a little slower, and require more api calls, but it should make it more accurate.

**Comment by etianen** [comment]
I'd happily take a pull request for this. Otherwise, I'll look into it
myself when the current work deadline has passed in a few days.

**Comment by kencochrane** [comment]
@etianen I added a PR here: https://github.com/etianen/django-s3-storage/pull/58 let me know what you think.
