### ISSUE TITLE
Upload file without storing whem on disk first

### ISSUE THREAD

**Issue by Smosker** [etianen/django-s3-storage#61]
Hello! I'm want to use a s3 storage, can you please tell me - can this module load files directly to s3 storage without storing whem localy first in some /tmp dir?

I have to work with big files and i dont want to store them localy before sending to s3 cloud.
thanks in advance for reply.

**Comment by etianen** [comment]
I'm afraid not. To upload them directly to S3 you need to use a combination
of server-side URL generation and client-side code to upload directly to
S3. It's not compatible with the Django file storage save() API, which
assumes the server has a file object representing the file data.

You could write you own code to save the file in S3 directly, then access
it via django-s3-storage. This is a good article on how to do the upload
part:

https://devcenter.heroku.com/articles/s3-upload-python

**Comment by Smosker** [comment]
thanks for answer!
