### ISSUE TITLE
Manually assigning existing S3 file to ImageField

### ISSUE THREAD

**Issue by sysradium** [etianen/django-s3-storage#66]
If I uploaded a file to s3 without django-s3-storage how easy is it to assign that file to a model without downloading it of s3 and uploading again?

Should I instantiate an `ImageField` and assign some `django_s3_storage.storage.S3File` object? If so then which fields are mandatory?

Thanks.

**Comment by etianen** [comment]
You can assign a string containing the name of the file in S3 to the model
field.

Something like this:

class YourModel(models.Model):
    image = models.ImageField(upload_to="foo/")

def view(request):
    # Save image on first model.
    obj_1 = YourModel()
    obj_1.image.save("image.jpg", request.FILES["some_image"])
    obj_1.save()
    # Also save image on second model.
    obj_2 = YourModel()
    obj_2.image = obj_1.image
    obj_2.save()

**Comment by sysradium** [comment]
Hold on, but this will upload the image?
All I have is the URL/name of the object in my S3 bucket.

**Comment by etianen** [comment]
Then simply assign obj.image to the name of the object in your S3 bucket

Images in the django database are just the name of the image in the file
storage.
