### ISSUE TITLE
In AWS Lambda, InvalidAccessKeyId error unless AWS_SESSION_TOKEN is given

### ISSUE THREAD

**Issue by ceefour** [etianen/django-s3-storage#68]
Using django-s3-storage in Lambda (for example with zappa) will throw [InvalidAccessKey error](https://stackoverflow.com/a/47740672/122441) because it doesn't give `AWS_SESSION_TOKEN` which is required for [temporary security credentials given by Lambda](http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#UsingTemporarySecurityCredentials). e.g.

```
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.
```

How to fix this:

1. Support `AWS_SESSION_TOKEN` in Django `settings.py` (and also add it to README/docs)
2. [Pass that token to boto3](http://boto3.readthedocs.io/en/latest/guide/configuration.html)

**Comment by etianen** [comment]
I've added this feature to the master branch. Please let me know if it works for you.

**Comment by thesunlover** [comment]
how to use AWS_SESSION_TOKEN to overcome this issue?
The generated by `aws sts get-token` AWS_SESSION_TOKEN  is only valid for a limited time ... so i cannot start the server for unlimited period with this token

**Comment by ceefour** [comment]
Thank you @etianen 

AFAIK `AWS_SESSION_TOKEN` is used by AWS Lambda.
