### ISSUE TITLE
Feature request: Add a dir prefix option to directory

### ISSUE THREAD

**Issue by busla** [etianen/django-s3-storage#7]
Would be great if I I could add a directory prefix setting to uploaded files so I can use the same bucket for different projects.

Example:

my-s3-bucket-name/project1/media
my-s3-bucket-name/project2/media

Here, `project1` and `project2` would be added to e.g. `django_s3_storage.storage.dir_prefix` setting.

**Comment by etianen** [comment]
You can use AWS_S3_KEY_PREFIX and AWS_S3_KEY_PREFIX_STATIC to do just this!
:)

https://github.com/etianen/django-s3-storage#available-settings

**Comment by busla** [comment]
Ohh, thought it was for file prefixing :-)


I suggest the following changes to the docs:

Current:
`# A prefix to add to the start of all uploaded files.`

Suggestion:
`# A prefix to add to the start of all uploaded files, e.g. a directory name to upload files to a subfolder in your bucket`

**Comment by etianen** [comment]
Well, if you end it in a slash, it'll be a directory. If you don't, it'll
be a file prefix.

S3 doesn't really have much concept of directories. It's a key prefix for
S3 keys.

**Comment by pljspahn** [comment]
I know this is old, but how would I use a prefix based on the value of a related field?

I would like all images to be in a folder named with the value of a `sku` field I have on the related model.

```
class Mymodel(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, default='', blank=True)
    sku = models.CharField(max_length=12)
    description = models.TextField()

    class Meta:
        ordering = ['sku']

    def __str__(self):
        return self.name


class Myimage(models.Model):
    name = models.CharField(max_length=100)

    # How can I append the upload_to value with the sku value of the related model?
    image = models.ImageField(upload_to='images')

    description = models.CharField(max_length=100, default='', blank=True)
    related_model = models.ForeignKey(Mymodel, on_delete=models.CASCADE, related_name='images')

    def __str__(self):
        return self.image.url
```

**Comment by etianen** [comment]
This can't be done using the features available in the Django file field.
Sorry.
