### ISSUE TITLE
Unable pickle File objects with s3 stprage for django celery tasks

### ISSUE THREAD

**Issue by MikeVL** [etianen/django-s3-storage#70]
```
EncodeError: Can't pickle <class 'botocore.client.S3'>: attribute lookup botocore.client.S3 failed
```

**Comment by etianen** [comment]
You can't pickle normal Python file objects. Why would you expect to be able to pickle a file stream from S3?

**Comment by etianen** [comment]
To pickle the file, instead `read()` the entire file into memory, and pickle that. Alternatively, pickle `file.name`, and use `default_file_storage.load()` in your celery task.
