### ISSUE TITLE
403 error with version 1.6.3 of boto3

### ISSUE THREAD

**Issue by adamyala** [etianen/django-s3-storage#74]
django version: 2.0.2
django-s3-storage version: 0.12.4
boto3 version: 1.6.3

Uploading a file then accessing the url results in a 403 error with the message:
```
The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

Last version of boto3 I used that made django-s3-storage work was 1.5.2. This time version 1.6.3 autoinstalled as a dep and it threw the above error.

As always, thank you for such a wonderful module.

**Comment by etianen** [comment]
I just updated the boto3 dependency to 1.6.3, and I can't reproduce this
error.

I bet it's something like boto3 1.6.3 uses a different default signature
method that your particular endpoint does not support?

What S3 region are you using?

Meanwhile, you can pin the boto3 version in your requirements.txt file or
similar to one that works.

**Comment by adamyala** [comment]
I sat down to recreate today and the problem went away. No idea why. Apologies for eating up some of your time.

If the issue comes back I'll reopen.

**Comment by etianen** [comment]
No worries!

**Comment by adamyala** [comment]
@etianen I'd like to reopen this issue and help debug the underlying cause. I have the latest boto3 version installed (1.9.27) and this bug reappeared. I downgraded to 1.5.2 per my note above to see if that would fix it, and it did fix it.

What information can I supply to start our research?

**Comment by adamyala** [comment]
Below are my settings:
```
DEFAULT_FILE_STORAGE = 'django_s3_storage.storage.S3Storage'
STATICFILES_STORAGE = 'django_s3_storage.storage.StaticS3Storage'
# The AWS region to connect to.
AWS_REGION = 'us-west-2'
# The AWS access key to use.
AWS_ACCESS_KEY_ID = 'XXXX'
# The AWS secret access key to use.
AWS_SECRET_ACCESS_KEY = 'XXXX'
# The name of the bucket to store files in.
AWS_S3_BUCKET_NAME = AWS_S3_BUCKET_NAME_STATIC = 'XXXXX'
```
Note that this only seems to be failing locally (while developing on my laptop). When running on a server things seem fine.

**Comment by etianen** [comment]
I'm afraid that I'm not really able to look into this myself at the moment.
If you can submit a pull request that fixes the issue for you, I'd be happy
to review and merge.

**Comment by Tjorriemorrie** [comment]
I'm also getting a 403. Do I need to change the settings of the bucket or anything else?

**Comment by vesatoivonen** [comment]
The same thing was happening to me yesterday, but once i started to debug the issue today it seems to have vanished.
I did not change any packages in between.

boto3==1.9.127
Django==2.2
django-s3-storage==0.12.4

**Comment by kciredor** [comment]
Same here. Pinning boto3 to 1.5.2 solved it immediately.

**Comment by etianen** [comment]
Ideally someone would reproduce this issue using the latest boto and make a
PR. Then we can specify a minimum version of boto3 in `setup.py`.#

Until then, pinning boto3 to a working version is the correct workaround.

**Comment by wesleykendall** [comment]
@etianen and others, I had this error until I found this https://github.com/boto/boto3/issues/1644#issuecomment-434566036

To get rid of this error, set the following settings:

```
AWS_S3_ADDRESSING_STYLE = 'path'
```

Now I successfully can view objects with boto3=1.14.45  and django-s3-storage="0.13.3"

@etianen do you think this should be changed to the default setting? I'm happy to open a PR. A better solution might be adjusting this based on the boto3 version, but I'm not sure if I will have time to make that PR

**Comment by etianen** [comment]
Do you have any idea why the current `auto` setting fails, but `path` does
not? That sounds very much like a problem with boto3.

**Comment by tomwojcik** [comment]
I struggled with lots of errors but finally managed to make it work (for `generate_presigned_post`).

I get my client from (if you need it)

```
client = S3Boto3Storage().bucket.meta.client
```
And those are the settings you need to experiment with

```
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = 'path'
AWS_S3_REGION_NAME = ...  # might be necessary
```
