### ISSUE TITLE
CacheControl header should be optional

### ISSUE THREAD

**Issue by manuganji** [etianen/django-s3-storage#78]
Hi, I want the ability to tune the caching from the AWS S3 console and I see in the [source](https://github.com/etianen/django-s3-storage/blob/master/django_s3_storage/storage.py#L221) that `CacheControl` header is always set even for public buckets.

`django-storages` doesn't touch caching in the S3 backend. I believe that's the correct way to do it.

**Comment by etianen** [comment]
Not setting cache-control will ruin performance for the common case. I
think setting cache-control by default is correct.

Can't you just override cache-control from the aws console?
