### ISSUE TITLE
Images uploaded to AWS s3 via ckeditor expire after one hour

### ISSUE THREAD

**Issue by peter-doherty** [etianen/django-s3-storage#82]
I'm using django 2.1.2 with django s3 storage, zinnia and ckeditor.

I can upload files to AWS s3 perfectly but files uploaded via CKeditor disappear after 60mins.

How can I fix this? It seems like the new url is not updating to my setup.

Thanks

**Comment by etianen** [comment]
In your settings, set:

AWS_S3_BUCKET_AUTH = False

This will make all uploaded files have public read permission, and prevent
the URL from expiring after 1 hour.

After updating this setting, you will need to run:

./manage.py s3_sync_meta django.core.files.storage.default_storage

https://github.com/etianen/django-s3-storage#file-storage-settings

**Comment by newatomuniverse** [comment]
It's not working. Any other solution?

**Comment by etianen** [comment]
In what way not working?

**Comment by newatomuniverse** [comment]
The image still gone after certain amount of time.
And I can't use s3_sync_meta django.core.files.storage.default.storage on my terminal.
Not recognized.

Please advise. Thanks

**Comment by etianen** [comment]
What error do your get when trying to run the sync meta command?
