### ISSUE TITLE
Question: how use encryption dynamically for some files

### ISSUE THREAD

**Issue by mark-mishyn** [etianen/django-s3-storage#85]
First of all thank you for your work and awesome open source lib.

I have a question about encryption. Lets say I have simple model:
```
class File(models.Model):
   os_file = models.FileField()
   is_encrypted = models.BooleanField(default=False)
```
... and I want encrypt only those `File` instances which has `is_encrypted=True`. Any suggestions how to do it properly?

**Comment by etianen** [comment]
I don't think that's possible using the Django file storage API. The
storage backend associated with a field can't be altered by another field
on the model.

It's probably easier to just encrypt all the files, as the overhead for AWS
at-rest encryption is very low.

**Comment by mark-mishyn** [comment]
@etianen Thank you for great answer!
