### ISSUE TITLE
FileField.size returns compressed size when gzip is used

### ISSUE THREAD

**Issue by emesik** [etianen/django-s3-storage#87]
I have `AWS_S3_GZIP=True` by default and I want to keep it that way. However, I'd like to be able to learn the uncompressed size of the file. The simplest way, `FileField.size` returns the size after compression and I see no other attribute or method of `FileField` that could return more info.

If I understand correctly, the `HEAD` response from S3 returns `ContentLength` of the data about to be transmitted, which means the gzipped version that is going to be served and further decompressed on client's side.

The S3 web interface also reports only compressed size in file properties. However, the bucket listings in S3 web interface display sizes of uncompressed objects, so I guess the information can be retrieved somehow.

**Comment by etianen** [comment]
Happy to review a MR that fixes this. Don't have the time to write it
myself right now. :)

I'd not worry about preserving the existing behavior, as it's definitely a
bug, not a feature!

**Comment by emesik** [comment]
Understood :) This is not the top priority for me ATM, but it landed on the TODO list and perhaps will be done someday.
