### ISSUE TITLE
Collectstatic fails with wrong AWS Key

### ISSUE THREAD

**Issue by edcu-web** [etianen/django-s3-storage#89]
This has got me stumped - 

When I've ran collectstatic, Ive received an error that the AWS key ID is incorrect. I made a new set and still got the same error. Checked keys were being sent at the time of being called. Ran a few print statements in Botocore/client.py and found that a js file for admin is being sent as an API param instead of my keys.

I have read others errors of it can fail when there is a missing file. The file that comes up does exist and runs fine in dev mode.

I'm not sure how to fix this and I'm not sure if this is a bug or I have missed something. 
Here are my errors + config: 
**Error:** [dpaste/8Miz (Python)](https://dpaste.de/8Miz)
**Djangos3-aws-settings:** [dpaste/38h6 (Python)](https://dpaste.de/38h6)
**Production_settings:**[dpaste/ESVC (Python)](https://dpaste.de/ESVC)
**Base_settings:**[dpaste/JHv9 (Python)](https://dpaste.de/JHv9)

**Comment by edcu-web** [comment]
Decided to use another package instead.

**Comment by edgarroman** [comment]
Were you getting an access denied result?  If so, it could have been due to your bucket settings.
