### ISSUE TITLE
Using the s3_sync_meta command causes an AttributeError exception

### ISSUE THREAD

**Issue by chrisjakuta** [etianen/django-s3-storage#94]
AttributeError: 'CompressedManifestStaticFilesStorage' object has no attribute 'sync_meta_iter'. 

I have the correct storage engine `django_s3_storage.storage.ManifestStaticS3Storage` - but when I run the `s3_sync_meta django.contrib.staticfiles.storage.staticfiles_storage` command I get this error. `CompressedManifestStaticfilesStorage` is one of the storage classes from `django.contrib.staticfiles.storage.staticfiles_storage`  Isn't this supposed to call the `django_s3_storage.storage` class `ManifestStaticS3Storage` ?

**Comment by etianen** [comment]
Can I have the full traceback please?

**Comment by chrisjakuta** [comment]
Yes, here is the traceback. 

`(lilywork) Christophers-MacBook-Pro:nerd_rich prosoft$ ./manage.py s3_sync_meta django.contrib.staticfiles.storage.staticfiles_storage --settings=nerd_rich.local_settings
Syncing meta for django.contrib.staticfiles.storage.staticfiles_storage
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/prosoft/lilywork/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/prosoft/lilywork/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/prosoft/lilywork/lib/python3.5/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/prosoft/lilywork/lib/python3.5/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/Users/prosoft/lilywork/lib/python3.5/site-packages/django_s3_storage/management/commands/s3_sync_meta.py", line 30, in handle
    for path in storage.sync_meta_iter():
  File "/Users/prosoft/lilywork/lib/python3.5/site-packages/django/utils/functional.py", line 214, in inner
    return func(self._wrapped, *args)
AttributeError: 'CompressedManifestStaticFilesStorage' object has no attribute 'sync_meta_iter'`

**Comment by etianen** [comment]
Where are you getting CompressedManifestStaticfilesStorage from?

It sounds like you're not using django-s3-storage for static files.

Can I see your settings.py file?

**Comment by chrisjakuta** [comment]
Yes, this the problem I thought I was having. Apparently, even though my settings include changing the static files storage engine, I am still somehow calling the default engine. 

My `local_settings.py` file 

`STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'homepage/static/homepage/'),
)
STATIC_ROOT = 'storages.backends.s3boto3.S3Boto3Storage'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SITE_ID = 1
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 3600
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_PRELOAD = True
AWS_STORAGE_BUCKET_NAME = 'nerdrich'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_LOCATION = 'static/'
STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, 'media')
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DEFAULT_FILE_STORAGE = 'storage_backends.MediaStorage'
AWS_DEFAULT_ACL = None
django_heroku.settings(locals())`

**Comment by chrisjakuta** [comment]
Ok, so I figured out what the problem was. The code `dragon_heroku.settings(locals())` will copy the setting files from the Heroku server and place them in the local virtual environment. Because of this, it will overwrite the existing local settings. Which is why `whitenoise.storage.CompressedManifestStaticFilesStorage` was called instead of django_s3_storage. This package did not cause this error.
